project_root: /project
data_dir: /project/data/FilteredCleanProcessed
log_root: /project/results/logs
origin_data: TaxolDataset
fixed_split: true
split_path: /project/data/splits/FilteredCleanProcessed_new

seed: 42
mode: 0_vs_0.1_vs_1
frozen: true
device: cuda
n_workers: 0
batch_size: 256
with_augs: true
debug: false
backbone: resnet152
n_layers: 2
wandb_offline: false
