project_root: ..
data_dir: ../data/FilteredCleanProcessed
log_root: ../results/logs
origin_data: TaxolDataset
fixed_split: true
split_path: ../data/splits/FilteredCleanProcessed_new

seed: 42
mode: 0.1_vs_1
frozen: true
device: cpu
n_workers: 4
batch_size: 32
with_augs: true
debug: true
backbone: resnet18
n_layers: 2
wandb_offline: true
