project_root: ..
data_root: ../data
log_root: ../results/logs
data: FilteredCleanProcessed
origin_data: TaxolDataset
fixed_split: true
split_path: ../data/splits/FilteredCleanProcessed

seed: 42
mode: 0_vs_1
frozen: true
num_epoch: 1
device: cpu
n_workers: 4
batch_size: 32
with_augs: true
debug: true
backbone: resnet18
tta: true
n_layers: 2
main_metric: accuracy01
